### ISSUE TITLE
请问五组seed中出现有一组实验的AUROC测试远小于训练（91vs80）可能是什么原因呢？有遇到过类似情况吗？

### ISSUE THREAD

**Issue by syfalbert** [zangzelin/code_USD#1]

**Comment by Shawn86CN** [comment]
请问您有遇到过FileNotFoundError: [Errno 2] No such file or directory:'save_near_index/SWat_near10_traintrain_windowsize60_trainsplit0.6_seed18_622.pkl'问题么

**Comment by zangzelin** [comment]
怀疑是随机数造成的，换几个种子试试
